logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG

spring:
  application:
    name: section-2-chat-gemini-advanced
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-3.5-flash
          temperature: 0.2
          max-output-tokens: 1024
          stop-sequences: [ "##STOP", "##END" ]
          #thinking-level: medium
