spring:
  application:
    name: section-2-chat-interaction
  profiles:
    active: gemini
  docker:
    compose:
      enabled: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:REPLACE_WITH_YOUR_KEY}

