server:
  port: 6062

logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
app:
  finnhub:
    api-key: ${FINNHUB_API_KEY}

spring:
  application:
    name: section-9-mcp-server-async
  ai:
    mcp:
      server:
        name: stock-market-mcp-server-async
        version: 1.0.0  #default
        type: ASYNC
        instructions: "This server provides STOCK information tools and resources (ASYNC)"
        protocol: streamable
        streamable-http:
          mcp-endpoint: /mcp #default
        capabilities:
          tool: true #default
          resource: true #default
          prompt: true #default


