server:
  port: 6062

logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: mappings
app:
  finnhub:
    api-key: ${FINNHUB_API_KEY}

spring:
  application:
    name: section-9-mcp-server-webflux
  ai:
    mcp:
      server:
        name: stock-market-mcp-server-webflux
        version: 1.0.0
        type: ASYNC
        instructions: "This server provides STOCK information tools and resources ( ASYNC)"
        protocol: streamable
        streamable-http:
          mcp-endpoint: /mcp
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true


