logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG

spring:
  application:
    name: section-5-chat-ollama
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
#     openai:
#       base-url: http://localhost:12434/v1
#       api-key: dummy-key-for-local-docker
#       chat:
#         model: ai/gemma3

